---
- name: Install Java 1.8 and some basic dependencies
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
   - unzip
   - screen
   - java-1.8.0-openjdk
   - libselinux-python
   - libsemanage-python


- name: Extract archive
  unarchive: 
    dest: /opt/ 
    src: /tmp/jboss-eap-7.0.0.zip 

- name: Add group "jboss"
  group: 
    name: jboss

- name: Add user "jboss"
  user: 
    name: jboss 
    group: jboss 
    home: /opt/jboss-eap-7.0
    
- name: Copy standalone config in place
  copy:
    src: standalone.xml
    dest: /opt/jboss-eap-7.0/standalone/configuration
    
- name: Copy eap startup config in place
  copy:
    src: jboss-eap.conf
    dest: /etc/default

- name: Change ownership of JBoss installation
  file: 
    path: /opt/jboss-eap-7.0/
    owner: jboss 
    group: jboss 
    state: directory 
    recurse: yes

- name: Copy the init script
  copy: 
    src: jboss-eap-standalone.service 
    dest: /etc/systemd/system/jboss-eap-standalone.service 
    mode: 0755

- name: Enable jboss systemd service
  systemd: 
    name: jboss-eap-standalone
    daemon_reload: yes
    enabled: yes
    masked: no

- name: Create default JBoss admin user
  command: "/opt/jboss-eap-7.0/bin/add-user.sh -s -r ManagementRealm -u admin -p jboss-123"

- name: Run Jboss eap in standalone mode
  command: "screen -dmS name /opt/jboss-eap-7.0/bin/standalone.sh "

#- name: Workaround for systemd bug
#  shell: systemctl start jboss-eap && chkconfig jboss on
#  ignore_errors: yes

#- name: Enable JBoss to be started at boot
#  service: 
#    name: jboss-eap 
#    enabled: yes 
#    state: started
